version: '3.5'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pagamentos_db
    ports:
      - "3306:3306"
    networks:
      - pagamentos_app_network
    expose:
      - 3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_HOST: 'mysql:3306/pagamentos_db'
      DB_USER: 'root'
      DB_PASS: '123456'
    ports:
      - "8080:8080"
    networks:
      - pagamentos_app_network
    depends_on:
      mysql:
        condition: service_healthy
      mock:
        condition: service_started

  mock:
    image: wiremock/wiremock
    ports:
      - "8081:8080"
    networks:
      - pagamentos_app_network
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/logs:/home/wiremock/logs

networks:
  pagamentos_app_network:
    name: "pagamentos_app_network"
    driver: bridge