version: '3.5'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - pagamentos_network
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pagamentos_db
    ports:
      - "3306:3306"
    networks:
      - pagamentos_network
    expose:
      - 3306

  pagamentos:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_HOST: 'mysql:3306/pagamentos_db'
      DB_USER: 'root'
      DB_PASS: '123456'
      AWS_ACCESS_KEY_ID: 'admin'
      AWS_SECRET_ACCESS_KEY: 'admin'
      AWS_REGION: 'us-east-1'
    ports:
      - "8080:8080"
    networks:
      - pagamentos_network
    depends_on:
      mysql:
        condition: service_healthy
      mock:
        condition: service_started

  mock:
    image: wiremock/wiremock
    ports:
      - "8081:8080"
    networks:
      - pagamentos_network
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/logs:/home/wiremock/logs

networks:
  pagamentos_network:
    name: "pagamentos_network"
    driver: bridge